# Generated by Django 3.1.3 on 2020-11-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201108_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_response',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
